function t389_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t450_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');$('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*=#]').click(function(){var url=$(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
t450_closeMenu()});$(document).keydown(function(e){if(e.keyCode==27){$('body').removeClass('t390__body_popupshowed');$('.t390').removeClass('t390__popup_show')}})}
function t450_closeMenu(){$('body').removeClass('t450__body_menushowed');$('.t450').removeClass('t450__menu_show');$('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=$('#rec'+recid).find('.t450');var windowheight=$(window).height()-80;var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')}}
function t450_appearMenu(recid){var el=$('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=$('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
$('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)})}
function t486_setHeight(recid){var el=$('#rec'+recid);var window_width=$(window).width();if(window_width>980){el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').innerWidth());var textwrapper=el.find('.t486__textwrapper');var blockimg=el.find('.t486__imgcontainer');textwrapper.css('height',blockimg.innerHeight())}else{el.find('.t486__blockimg').css('height',el.find('.t486__blockimg').width());el.find('.t486__textwrapper').css('height','auto')}}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).load(function(){t570_setMapHeight(recid)});$(window).resize(function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t602_init(recid){var t602_lastCall,t602_timeoutId,t602_interval=100;$(window).scroll(function(){var t602_now=new Date().getTime();if(t602_lastCall&&t602_now<(t602_lastCall+t602_interval)){clearTimeout(t602_timeoutId);t602_timeoutId=setTimeout(function(){t602_lastCall=t602_now;t602_setProgressBarWidth(recid)},t602_interval-(t602_now-t602_lastCall))}else{t602_lastCall=t602_now;t602_setProgressBarWidth(recid)}})}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=$(window).scrollTop(),t602_docHeight=$(document).height(),t602_winHeight=$(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;$(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t635_init(recid){t635_startType(recid)}
function t635_startType(recid){var t635_el=$('#rec'+recid),t635_data=t635_el.find(".t635__textholder"),t635_animRecId=t635_data.attr("data-recid"),t635_animText=t635_findAnimElem(t635_animRecId),t635_phrasesList=[],t635_phrase1=t635_data.attr("data-text1"),t635_phrase2=t635_data.attr("data-text2"),t635_phrase3=t635_data.attr("data-text3"),t635_phrase4=t635_data.attr("data-text4"),t635_phrase5=t635_data.attr("data-text5"),t635_speed=t635_data.attr("data-speed"),t635_loop=t635_data.attr("data-loop"),t635_backspaceDelay=t635_data.attr("data-backspacing-delay");if(typeof t635_animText=="undefined"){return}
if(typeof t635_phrase1!="undefined"){t635_phrasesList.push(t635_phrase1.slice(0,80))}
if(typeof t635_phrase2!="undefined"){t635_phrasesList.push(t635_phrase2.slice(0,80))}
if(typeof t635_phrase3!="undefined"){t635_phrasesList.push(t635_phrase3.slice(0,80))}
if(typeof t635_phrase4!="undefined"){t635_phrasesList.push(t635_phrase4.slice(0,80))}
if(typeof t635_phrase5!="undefined"){t635_phrasesList.push(t635_phrase5.slice(0,80))}
if(t635_animText.length!=0&&t635_phrasesList.length!=0){var t635_animTextHtml=t635_animText.html(),t635_animTextSplitted=t635_animTextHtml.split("|"),t635_curWin=$(window);t635_animText.html(t635_animTextSplitted[0]+"<span class=\"t635__typing-text\"></span>"+t635_animTextSplitted[1]);t635_updateAnimTextLimits(t635_animRecId);t635_curWin.bind('resize',t_throttle(function(){t635_updateAnimTextLimits(t635_animRecId)},200));setInterval(function(){t635_updateAnimTextLimits(t635_animRecId)},5000);var t635_animatedText=$("#rec"+t635_animRecId+" .t635__typing-text"),t635_animTextTop=t635_animatedText.attr("data-top-limit"),t635_animTextBottom=t635_animatedText.attr("data-bottom-limit"),t635_winTop=t635_curWin.scrollTop(),t635_winBottom=t635_winTop+t635_curWin.height();t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay);if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}
t635_curWin.bind('scroll',t_throttle(function(){t635_animTextTop=t635_animatedText.attr("data-top-limit");t635_animTextBottom=t635_animatedText.attr("data-bottom-limit");t635_winTop=t635_curWin.scrollTop();t635_winBottom=t635_winTop+t635_curWin.height();if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}else{$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').continueTyping()}},200))}}
function t635_findAnimElem(animRecId){var animRec=$("#rec"+animRecId);var animH1=animRec.find("h1:contains(\'|\')").last();var animH2=animRec.find("h2:contains(\'|\')").last();var animH3=animRec.find("h3:contains(\'|\')").last();var animDiv=animRec.find("div:contains(\'|\')").last();if(typeof animH1!="undefined"&&animH1.length>0){return animH1}
if(typeof animH2!="undefined"&&animH2.length>0){return animH2}
if(typeof animH3!="undefined"&&animH3.length>0){return animH3}
if(typeof animDiv!="undefined"&&animDiv.length>0){return animDiv}}
function t635_updateAnimTextLimits(t635_animRecId){var t635_animatedBlock=$("#rec"+t635_animRecId),t635_animatedText=t635_animatedBlock.find(".t635__typing-text");t635_animatedText.attr("data-top-limit",t635_animatedText.offset().top);t635_animatedText.attr("data-bottom-limit",(t635_animatedBlock.offset().top+t635_animatedBlock.height()))}
function t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay){if(typeof t635_speed=="undefined"){t635_speed=40}
if(typeof t635_backspaceDelay=="undefined"){t635_backspaceDelay=800}
if(typeof t635_loop=="undefined"){t635_loop=!0}else{t635_loop=!1}
$("#rec"+t635_animRecId+" .t635__typing-text").typed({strings:t635_phrasesList,typeSpeed:t635_speed*1,startDelay:600,backSpeed:10,backDelay:t635_backspaceDelay*1,loop:t635_loop,contentType:'text'})}
function t774_init(recid){t774_unifyHeights(recid);$(window).bind('resize',t_throttle(function(){t774_unifyHeights(recid)},200));$(".t774").bind("displayChanged",function(){t774_unifyHeights(recid)});$(window).load(function(){t774_unifyHeights(recid)})}
function t774_unifyHeights(recid){var t774_el=$('#rec'+recid),t774_blocksPerRow=t774_el.find(".t774__container").attr("data-blocks-per-row"),t774_cols=t774_el.find(".t774__content"),t774_mobScroll=t774_el.find(".t774__scroll-icon-wrapper").length;if($(window).width()<=480&&t774_mobScroll==0){t774_cols.css("height","auto");return}
var t774_perRow=+t774_blocksPerRow;if($(window).width()<=960&&t774_mobScroll>0){var t774_perRow=t774_cols.length}
else{if($(window).width()<=960){var t774_perRow=2}}
for(var i=0;i<t774_cols.length;i+=t774_perRow){var t774_maxHeight=0,t774_row=t774_cols.slice(i,i+t774_perRow);t774_row.each(function(){var t774_curText=$(this).find(".t774__textwrapper"),t774_curBtns=$(this).find(".t774__btn-wrapper, .t774__btntext-wrapper"),t774_itemHeight=t774_curText.outerHeight()+t774_curBtns.outerHeight();if(t774_itemHeight>t774_maxHeight){t774_maxHeight=t774_itemHeight}});t774_row.css("height",t774_maxHeight)}}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.attr("data-record-type")=="215"||curRec.attr("data-record-type")=="706"){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}
function t830_init(recid){var rec=$('#rec'+recid);var allrecords=$("#allrecords");var el=rec.find('.t830');var panel=rec.find('.t830__panel');var overlay=rec.find('.t830m__overlay');var menu=rec.find('.t830m');var submenu=rec.find('.t830m__submenu');var burger=rec.find('.t830__side .t830__burger');var menuItem=rec.find('.t830m__list-title a');var submenuItem=rec.find('.t830m__submenu-item a');if($(window).width()>1259){$('.t-body').prepend(rec);allrecords.addClass('t830__allrecords');$('.t-tildalabel').addClass('t830__t-tildalabel')}
t830_initMenu(rec,menu,burger);t830_removePadding(rec,allrecords);t830_calcCol(rec,menu,allrecords);t830_menuHighlight();t830_submenuHighlight();t830_openSubmenu(rec);t830_hoverShowMenu(rec,menu,panel,overlay,burger);$(window).resize(function(){t830_calcCol(rec,menu,allrecords);t830_removePadding(rec,allrecords);if(menu.hasClass('t830m_close')&&$(window).width()>1499){overlay.removeClass('t830m__menu_show')}});if(submenu.hasClass('t830m__submenu_close')){t830_toggleMenu(rec,submenu)}
if($(window).width()>1259){t830_scrollSideMenu(rec)}
menuItem.click(function(){if(window.location.hash.length!=0){menuItem.removeClass('t-active');$(this).addClass('t-active')}});submenuItem.click(function(){if(window.location.hash.length!=0){submenuItem.removeClass('t-active');$(this).addClass('t-active')}});t830_checkAnchorLinks(recid)}
function t830_calcCol(rec,menu,allrecords){if($(window).width()>1259&&!menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd');$('.t-tildalabel').addClass('t830__t-tildalabel_padd')}
if($(window).width()>1259&&menu.hasClass('t830m_open')){allrecords.addClass('t830__allrecords_padd-small');$('.t-tildalabel').addClass('t830__t-tildalabel_padd-small')}}
function t830_toggleMenu(rec,submenu){var listTitle=rec.find('.t830m__list-title_toggle');var submenu;var textTitle;listTitle.click(function(){submenu=$(this).next();textTitle=$(this).find('.t830m__list-title-text');submenu.slideToggle('slow');textTitle.toggleClass('t830m__list-title-text_opacity');textTitle.toggleClass('t-menu__link-item')})}
function t830_openSubmenu(rec){var submenuItem=rec.find('.t830m__submenu-item a.t-active');submenuItem.parents('.t830m__submenu').css('display','block')}
function t830_hoverShowMenu(rec,menu,panel,overlay,burger){if($(window).width()>1259&&panel.hasClass('t830__panel_hover')){panel.mouseenter(function(e){menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')});menu.mouseleave(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});overlay.mouseenter(function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');overlay.removeClass('t830m__overlay_hover')})
menu.find('a').on('click',function(){menu.removeClass('t830m__menu_show');burger.removeClass('t830__burger_open')});burger.click(function(){if(burger.hasClass('t830__burger_open')){t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')}else{menu.addClass('t830m__menu_show');burger.addClass('t830__burger_open');overlay.addClass('t830m__overlay_hover')}})}}
function t830_showMenu(rec,menu,burger){var panel=rec.find('.t830__panel');$('body').addClass('t830__body_menushowed');rec.find('.t830m').addClass('t830m__menu_show');rec.find('.t830m__overlay').addClass('t830m__menu_show');rec.find('.t830m__overlay, .t830m__close, a[href*=#]').click(function(){if($(this).is('.tooltipstered, .t794__tm-link')){return}
t830_closeMenu(rec,menu);burger.removeClass('t830__burger_open')});panel.addClass('t830__panel_close');$(document).keydown(function(e){if(e.keyCode==27){if($('.t-site-search-popup__background').length===0){$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');burger.removeClass('t830__burger_open');$('.t830m__overlay').removeClass('t830m__menu_show')}}})}
function t830_closeMenu(rec,menu){var panel=rec.find('.t830__panel');if(menu.hasClass('t830m_open')&&$(window).width()<1500){panel.removeClass('t830__panel_close')}
$('body').removeClass('t830__body_menushowed');$('.t830m').removeClass('t830m__menu_show');$('.t830m__overlay').removeClass('t830m__menu_show')}
function t830_initMenu(rec,menu,burger){var obj=rec.find('.t830__menu__content');var panel=rec.find('.t830__panel');var menu=rec.find('.t830m');if(panel.hasClass('t830__panel_click')||(panel.hasClass('t830__panel_hover')&&$(window).width()<=1259)){obj.click(function(e){if(menu.hasClass('t830m__menu_show')){burger.removeClass('t830__burger_open');t830_closeMenu(rec,menu)}else{burger.addClass('t830__burger_open');t830_showMenu(rec,menu,burger)}
e.preventDefault()})}
$('.t830').bind('clickedAnchorInTooltipMenu',function(){t830_closeMenu(rec,menu)})}
function t830_menuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$(".t830m__list-title a[href='"+url+"']").addClass('t-active');$(".t830m__list-title a[href='"+url+"/']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"']").addClass('t-active');$(".t830m__list-title a[href='"+pathname+"/']").addClass('t-active');$(".t830m__list-title a[href='/"+pathname+"/']").addClass('t-active')}
function t830_submenuHighlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname="/"}
$(".t830m__submenu-item a[href='"+url+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+url+"/']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"']").addClass('t-active');$(".t830m__submenu-item a[href='"+pathname+"/']").addClass('t-active');$(".t830m__submenu-item a[href='/"+pathname+"/']").addClass('t-active')}
function t830_scrollSideMenu(rec){var container=rec.find('.t830m__container');container.on('scroll wheel DOMMouseScroll mousewheel',function(e){var searchResultContainer=rec.find('.t-site-search-dm');if(searchResultContainer.length==0){t830_stopScroll(this,e)}})}
function t830_stopScroll(block,eventScroll){var $this=$(block);var scrollTop=block.scrollTop;var scrollHeight=block.scrollHeight;var height=$this.height();var delta=(eventScroll.type=='DOMMouseScroll'?eventScroll.originalEvent.detail*-40:eventScroll.originalEvent.wheelDelta);var up=delta>0;var prevent=function(){eventScroll.stopPropagation();eventScroll.preventDefault();eventScroll.returnValue=!1;return!1}
if(!up&&-delta>scrollHeight-height-scrollTop){$this.scrollTop(scrollHeight);return prevent()}else if(up&&delta>scrollTop){$this.scrollTop(0);return prevent()}}
function t830_removePadding(rec,allrecords){if(rec.css('display')=='none'){allrecords.css('padding-left',0);$('.t-tildalabel').css('padding-left',0)}}
function t830_checkAnchorLinks(recid){if($(window).width()>=960){var submenuNavLinks=$("#rec"+recid+" .t830m__submenu-item a:not(.tooltipstered)[href*='#']");var menuNavLinks=$("#rec"+recid+" .t830m__menu-item a:not(.tooltipstered)[href*='#']");if(submenuNavLinks.length>0){setTimeout(function(){t830_catchScroll(submenuNavLinks,recid)},500)}
if(menuNavLinks.length>0){setTimeout(function(){t830_catchScroll(menuNavLinks,recid)},500)}}}
function t830_catchScroll(navLinks,recid){var rec=$('#rec'+recid);var clickedSectionId=null;var sections=new Array();var sectionIdTonavigationLink=[];var interval=100;var lastCall;var timeoutId;var navLinks=$(navLinks.get().reverse());navLinks.each(function(){var cursection=t830_getSectionByHref($(this));if(typeof cursection.attr('id')!='undefined'){sections.push(cursection)}
sectionIdTonavigationLink[cursection.attr('id')]=$(this)});t830_updateSectionsOffsets(sections);sections.sort(function(a,b){return b.attr('data-offset-top')-a.attr('data-offset-top')});$(window).bind('resize',t_throttle(function(){t830_updateSectionsOffsets(sections)},200));$('.t830').bind('displayChanged',function(){t830_updateSectionsOffsets(sections)});setInterval(function(){t830_updateSectionsOffsets(sections)},5000);t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId);navLinks.click(function(){var clickedSection=t830_getSectionByHref($(this));if(!$(this).hasClass('tooltipstered')&&typeof clickedSection.attr('id')!='undefined'){navLinks.removeClass('t-active');$(this).addClass('t-active');clickedSectionId=t830_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var now=new Date().getTime();if(lastCall&&now<(lastCall+interval)){clearTimeout(timeoutId);timeoutId=setTimeout(function(){lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)},interval-(now-lastCall))}else{lastCall=now;clickedSectionId=t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId)}})}
function t830_getSectionByHref(curlink){var curLinkValue=curlink.attr('href').replace(/\s+/g,'');if(curLinkValue[0]=='/'){curLinkValue=curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+curLinkValue.substring(1)+"']")}}
function t830_highlightNavLinks(navLinks,sections,sectionIdTonavigationLink,clickedSectionId){var scrollPosition=$(window).scrollTop();var valueToReturn=clickedSectionId;if(sections.length!=0&&clickedSectionId==null&&sections[sections.length-1].attr('data-offset-top')>(scrollPosition+300)){navLinks.removeClass('t-active');return null}
$(sections).each(function(e){var curSection=$(this);var sectionTop=curSection.attr('data-offset-top');var id=curSection.attr('id');var navLink=sectionIdTonavigationLink[id];if(((scrollPosition+300)>=sectionTop)||(sections[0].attr("id")==id&&scrollPosition>=$(document).height()-$(window).height())){if(clickedSectionId==null&&!navLink.hasClass('t-active')){navLinks.removeClass('t-active');navLink.addClass('t-active');valueToReturn=null}else{if(clickedSectionId!=null&&id==clickedSectionId){valueToReturn=null}}
return!1}});return valueToReturn}
function t830_updateSectionsOffsets(sections){$(sections).each(function(){var curSection=$(this);curSection.attr('data-offset-top',curSection.offset().top)})}
function t833_init(recid){t833_startAnimation(recid)}
function t833_showOnCertainWidth(el,wrapper){el.attr('class').split(' ').forEach(function(item){if(item.indexOf('t-screen')!==-1){wrapper.addClass(item)}})}
function t833_startAnimation(recid){var el=$('#rec'+recid);var wrapper=el.find('.t833__sliderwrapper');var wr=el.find('.t833');var recs=wr.attr('data-coverslider-rec-ids');t833_showOnCertainWidth(el,wrapper);if($('#allrecords').attr('data-tilda-mode')==='edit'){t833_addAnimation(el.find('.t833__demo'),wrapper);return}
if(typeof recs!=='undefined'){recs=recs.split(',');recs.forEach(function(rec,index,array){var curRec=$('#rec'+rec);var curWrapper=wrapper.clone().css('position','absolute');t833_addAnimation(curRec,curWrapper)})}else{var nextBlock=el.next(':has(.t-cover)');var prevBlock=el.prev(':has(.t-cover)');var curWrapper=wrapper.clone().css('position','absolute');if(nextBlock.length!==0){t833_addAnimation(nextBlock,curWrapper)}else if(prevBlock.length!==0){t833_addAnimation(prevBlock,curWrapper)}}}
function t833_addAnimation(curRec,wrapper){curRec.attr('data-animationappear','off').removeClass('r_hidden');var curRecType=curRec.attr('data-record-type');var curRecId=curRec.attr('id');if(curRecType==='396'){curRec.find('.t396__filter').after(wrapper);wrapper.css('z-index','0')}
var coverWrapper=curRec.find('.t-cover');if(coverWrapper.length>0){coverWrapper.find('.t-cover__filter').after(wrapper);wrapper.css('z-index','0')}
if(curRec.length!=0){$(window).load(function(){t833_changeSlide(curRec)})}
var slider=curRec.find('.t833__slider');var slide=curRec.find('.t833__slide');var numberOfSlides=slide.length;if(numberOfSlides===3||numberOfSlides===2){slide.clone().appendTo(slider)}}
function t833_changeSlide(curRec){var slide=curRec.find('.t833__slide');var firstSlide=curRec.find('.t833__slide:first-child');var numberOfSlides=slide.length;var i=1;firstSlide.addClass('t833__slide_fx1');window.setInterval(t833_kenBurns,5000);function t833_kenBurns(){if(i==numberOfSlides){i=0}
$(slide[i]).addClass('t833__slide_fx');if(i===0){$(slide[numberOfSlides-2]).removeClass('t833__slide_fx t833__slide_fx1')}
if(i===1){$(slide[numberOfSlides-1]).removeClass('t833__slide_fx t833__slide_fx1');slide.removeClass('t833__slide_opacity')}
if(i>1){$(slide[i-2]).removeClass('t833__slide_fx t833__slide_fx1')}
i++}}